import Navbar from "@/components/NavBar";
import { useContext } from "react";
import { MyContext } from "@/Context/context";
import Head from "next/head";
import { FaBirthdayCake, FaBook } from "react-icons/fa";
import { TbMessageLanguage } from "react-icons/tb";

export default function About() {
  const { darkMode } = useContext(MyContext);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Gustavo Vasconcelos Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://horizon-tailwind-react-git-tailwind-components-horizon-ui.vercel.app/static/css/main.ad49aa9b.css"
        />
        <title>Gustavo Vasconcelos About</title>
      </Head>
      <main className="bg-gray-600 md:px-4 lg:px-8 dark:bg-gray-900">
        <Navbar />
        <div className="flex flex-col justify-center items-center min-h-screen dark:bg-gray-900">
          <div className="w-full max-w-2xl mx-auto p-4 bg-white bg-clip-border shadow-lg rounded-md dark:bg-gray-600 dark:text-white dark:!shadow-none">
            <h4 className="text-2xl text-cyan-500 font-bold text-navy-700 dark:text-teal-300 mb-4">
              Sobre Mim
            </h4>
            <p className="text-base font-medium dark:text-white">
              Meu nome é Gustavo Vasconcelos Salomão, tenho 19 anos e sempre
              nutri uma paixão pela criação de soluções tecnológicas. Em maio de
              2022, entrei de cabeça no fascinante mundo da tecnologia,
              culminando na conclusão bem-sucedida de um curso abrangente de
              Desenvolvimento Full Stack pela Trybe. Agora, estou dando
              continuidade aos meus estudos na Unisagrado, localizada em
              Bauru-SP, aprimorando ainda mais minha base de conhecimentos.
              <br />
              <br />
              Minha jornada até aqui tem sido marcada pela dedicação e entusiasmo
              pela área de desenvolvimento. Agora, estou animado para dar o
              próximo passo em minha carreira profissional. Com uma formação
              sólida e a habilidade de enfrentar desafios de forma proativa,
              estou em busca da minha primeira oportunidade profissional para
              aplicar meu conhecimento, crescer profissionalmente e contribuir
              de maneira significativa para o mundo da tecnologia. Estou
              confiante de que a combinação da minha paixão, educação e vontade
              de aprender tornam-me um candidato promissor. Aguardo ansiosamente
              a chance de contribuir para projetos inovadores e continuar a
              trilhar meu caminho no campo da tecnologia.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mt-8 w-full max-w-2xl mx-auto">
            <div className="flex flex-col items-start justify-center bg-white bg-clip-border p-4 shadow-lg rounded-md dark:!bg-navy-700 dark:shadow-none">
              <p className="text-sm text-cyan-500 dark:text-teal-300 flex items-center">
                Instituição de ensino
                <FaBook className="ml-1" />
              </p>
              <p className="text-base font-medium text-navy-700 dark:text-white">
                Desenvolvedor Full Stack - Trybe
              </p>
              <p className="text-base font-medium text-navy-700 dark:text-white">
                Ciência da Computação - Unisagrado
              </p>
            </div>

            <div className="flex flex-col justify-center bg-white bg-clip-border p-4 shadow-lg rounded-md dark:!bg-navy-700 dark:shadow-none">
              <p className="text-sm text-cyan-500 dark:text-teal-300 flex items-center">
                Idiomas
                <TbMessageLanguage className="ml-1" />
              </p>
              <p className="text-base font-medium text-navy-700 dark:text-white">
                Português
              </p>
              <p className="text-base font-medium text-navy-700 dark:text-white">
                Inglês
              </p>
            </div>

            <div className="flex flex-col items-start justify-center bg-white bg-clip-border p-4 shadow-lg rounded-md dark:!bg-navy-700 dark:shadow-none">
              <p className="text-sm text-cyan-500 dark:text-teal-300">Contato</p>
              <p className="text-base font-medium text-navy-700 dark:text-white">
                Desenvolvedor Full-Stack
              </p>
            </div>

            <div className="flex flex-col justify-center bg-white bg-clip-border p-4 shadow-lg rounded-md dark:!bg-navy-700 dark:shadow-none">
              <p className="text-sm text-cyan-500 dark:text-teal-300 flex items-center">
                Aniversário
                <FaBirthdayCake className="ml-1" />
              </p>
              <p className="text-base font-medium text-navy-700 dark:text-white">
                25 de fevereiro de 2004
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
