import Head from 'next/head' 
import {AiFillLinkedin, AiFillGithub} from 'react-icons/ai'
import Image from 'next/image';
import myImage from '../public/boy.jpg'
import SolarSystem from '../components/SolarSystem'
import TFC from '../components/Tfc'
import TrybeTunes from '../components/TrybeTunes'
import { useContext } from 'react';
import { MyContext } from '../Context/context';
import Navbar from '../components/NavBar';
import Certificates from '@/components/Certificates';

export default function Home() {
  const {darkMode} = useContext(MyContext);
  return (
    <div className={darkMode? "dark": ""}>
      <Head>
        <title>Gustavo Vasconcelos Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <Navbar />
          <div className="text-center py-10">
            <h3 className="text-5xl py-2 text-teal-300 font-medium md:text-6xl"> Gustavo Vasconcelos </h3>
            <h4 className="text-2xl py-2 md:text-3xl dark:text-white">Eu sou um desenvolvedor Full Stack</h4>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
          <button><a target="_blank" className="hover:text-white" href="https://www.linkedin.com/in/vasconcelos-gu/" ><AiFillLinkedin /></a></button>
          <button><a target="_blank" className="hover:text-white" href="https://github.com/vasconcelosguu" ><AiFillGithub /></a></button>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20">
            <Image src={ myImage } alt="bonequinho icone"/>
          </div>
          <h3 className="text-center text-teal-300 py-5 m-20 font-medium text-5xl">Projetos Em Destaque</h3>
        </section>
        
          <section>
            <div className="lg:flex gap-10">
              <TrybeTunes />
              <SolarSystem />
              <TFC />
           </div>
          </section>

          <div>
          <h3 className="text-center text-teal-300 py-5 m-20 font-medium text-5xl">Meus Certificados</h3>
          </div>
          <section>
            <div className="lg:flex gap-10">
              <Certificates />
            </div>
          </section>
      </main>
    </div>
  );
}
